dataset_folder: datasets
out_folder: meta-features
save_strategy: json
datasets:
  - ada_agnostic.arff
  - anneal.arff
  - AR10P.arff
  - balance-scale.arff
  - car.arff
  - CLL-SUB-111.arff
  - cmc.arff
  - colon.arff
  - credit-g.arff
  - diabetes.arff
  - ECML90x27679.arff
  - ecoli.arff
  - Embryonaldataset_c.arff
  - flags.arff
  - GCM_Test.arff
  - gina_agnostic.arff
  - gina_prior.arff
  - gina_prior2.arff
  - glass.arff
  - grub-damage.arff
  - heart-statlog.arff
  - ionosphere.arff
  - iris.arff
  - kdd_JapaneseVowels_test.arff
  - kdd_JapaneseVowels_train.arff
  - kdd_synthetic_control.arff
  - kr-vs-kp.arff
  - leukemia.arff
  - Leukemia_3c.arff
  - leukemia_test_34x7129.arff
  - leukemia_train_38x7129.arff
  - lymph.arff
  - mfeat-fourier.arff
  - mfeat-morphological.arff
  - mfeat-pixel.arff
  - mfeat-zernike.arff
  - molecular-biology_promoters.arff
  - monks-problems-1_test.arff
  - monks-problems-1_train.arff
  - monks-problems-2_test.arff
  - monks-problems-2_train.arff
  - monks-problems-3_test.arff
  - monks-problems-3_train.arff
  - oh0.wc.arff
  - oh10.wc.arff
  - oh15.wc.arff
  - oh5.wc.arff
  - pasture.arff
  - pendigits.arff
  - PIE10P.arff
  - segment.arff
  - SMK-CAN-187.arff
  - solar-flare_1.arff
  - solar-flare_2.arff
  - sonar.arff
  - spect_test.arff
  - spect_train.arff
  - spectf_test.arff
  - spectf_train.arff
  - spectrometer.arff
  - splice.arff
  - sylva_agnostic.arff
  - sylva_prior.arff
  - TOX-171.arff
  - tr11.wc.arff
  - tr12.wc.arff
  - tr23.wc.arff
  - tr31.wc.arff
  - tr41.wc.arff
  - tr45.wc.arff
  - vehicle.arff
  - vowel.arff
  - wap.wc.arff
  - waveform-5000.arff
  - white-clover.arff
  - wine.arff
  - zoo.arff
