threads: 4
population: 10
generations: 50
folder: datasets/csv
datasets:
 - iris.csv
 - monks-problems-3_train.csv
 - monks-problems-1_train.csv
 - pasture.csv
 - monks-problems-2_train.csv
 - grub-damage.csv
 - zoo.csv
 - spect_train.csv
 - glass.csv
 - white-clover.csv
 - wine.csv
 - ecoli.csv
 - balance-scale.csv
 - monks-problems-3_test.csv
 - monks-problems-1_test.csv
 - monks-problems-2_test.csv
 - lymph.csv
 - heart-statlog.csv
 - spectf_train.csv
 - solar-flare_1.csv
 - spect_test.csv
 - flags.csv
 - diabetes.csv
 - molecular-biology_promoters.csv
 - car.csv
 - ionosphere.csv
 - solar-flare_2.csv
 - spectf_test.csv
 - mfeat-morphological.csv
 - sonar.csv
 - vowel.csv
 - cmc.csv
 - vehicle.csv
 - credit-g.csv
 - anneal.csv
 - kdd_synthetic_control.csv
 - segment.csv
 - spectrometer.csv
 - kdd_JapaneseVowels_train.csv
 - kdd_JapaneseVowels_test.csv
 - mfeat-zernike.csv
 - kr-vs-kp.csv
 - colon.csv
 - mfeat-fourier.csv
 - pendigits.csv
 - splice.csv
 - waveform-5000.csv
 - ada_agnostic.csv
 - leukemia_test_34x7129.csv
 - leukemia_train_38x7129.csv
 - AR10P.csv
 - Embryonaldataset_c.csv
 - mfeat-pixel.csv
 - PIE10P.csv
 - leukemia.csv
 - Leukemia_3c.csv
 - TOX-171.csv
 - tr23.wc.csv
 - sylva_prior.csv
 - tr12.wc.csv
 - gina_prior2.csv
 - gina_prior.csv
 - tr11.wc.csv
 - oh5.wc.csv
 - oh15.wc.csv
 - sylva_agnostic.csv
 - oh0.wc.csv
 - gina_agnostic.csv
 - oh10.wc.csv
 - tr45.wc.csv
 - tr41.wc.csv
 - wap.wc.csv
