dataset_folder: common-datasets
out_folder: results/single_algorithm_tuning
save_strategy: json
threads: 4

algorithms:
  - classifier:
      name                : "SVM"
      type                : "Classifier"
      classifier_class    : "weka.classifiers.functions.LibSVM"
      classifier_options  :
        -S: "0"
        -K: "2"
    params:
      - name: -G
        type: exp
        loose_start: -15
        loose_end: 3
        loose_step: 2
        fine_step: 0.25
      - name: -C
        type: exp
        loose_start: -5
        loose_end: 15
        loose_step: 2
        fine_step: 0.25

  - classifier:
      name                : "RF"
      type                : "Classifier"
      classifier_class    : "weka.classifiers.trees.RandomForest"
      classifier_options  : {}
    params:
      - name: -I
        type: lin
        loose_start: 10
        loose_end: 300
        loose_step: 10
        fine_step: 1
      - name: -K
        type: lin
        loose_start: 1
        loose_end: round(2 * sqrt(attributes))
        loose_step: round((end - start + 9) / 10)
        fine_step: 1

datasets:
  # all
  - ada_agnostic.csv
  - adult.csv
  - agaricus-lepiota.csv
  - allbp.csv
  - allhyper.csv
  - allhypo.csv
  - allrep.csv
  - analcatdata_aids.csv
  - analcatdata_asbestos.csv
  - analcatdata_authorship.csv
  - analcatdata_bankruptcy.csv
  - analcatdata_boxing1.csv
  - analcatdata_boxing2.csv
  - analcatdata_creditscore.csv
  - analcatdata_cyyoung8092.csv
  - analcatdata_cyyoung9302.csv
  - analcatdata_dmft.csv
  - analcatdata_fraud.csv
  - analcatdata_germangss.csv
  - analcatdata_happiness.csv
  - analcatdata_japansolvent.csv
  - analcatdata_lawsuit.csv
  - ann-thyroid.csv
  - anneal.csv
  - AR10P.csv
  - australian.csv
  - auto.csv
  - backache.csv
  - balance-scale.csv
  - biomed.csv
  - breast.csv
  - breast-cancer.csv
  - breast-cancer-wisconsin.csv
  - breast-w.csv
  - buggyCrx.csv
  - calendarDOW.csv
  - car.csv
  - car-evaluation.csv
  - cars.csv
  - cars1.csv
  - chess.csv
  - churn.csv
  - clean1.csv
  - clean2.csv
  - cleve.csv
  - cleveland.csv
  - cleveland-nominal.csv
  - CLL-SUB-111.csv
  - cloud.csv
  - cmc.csv
  - colic.csv
  - collins.csv
  - colon.csv
  - confidence.csv
  - connect-4.csv
  - corral.csv
  - credit-a.csv
  - credit-g.csv
  - crx.csv
  - dermatology.csv
  - diabetes.csv
  - dis.csv
  - dna.csv
  - ECML90x27679.csv
  - ecoli.csv
  - Embryonaldataset_c.csv
  - flags.csv
  - flare.csv
  - GAMETES_Epistasis_2-Way_20atts_0.1H_EDM-1_1.csv
  - GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1.csv
  - GAMETES_Epistasis_2-Way_1000atts_0.4H_EDM-1_EDM-1_1.csv
  - GAMETES_Epistasis_3-Way_20atts_0.2H_EDM-1_1.csv
  - GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_50_EDM-2_001.csv
  - GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_75_EDM-2_001.csv
  - german.csv
  - gina_agnostic.csv
  - gina_prior.csv
  - gina_prior2.csv
  - glass.csv
  - glass2.csv
  - grub-damage.csv
  - haberman.csv
  - hayes-roth.csv
  - heart-c.csv
  - heart-h.csv
  - heart-statlog.csv
  - hepatitis.csv
  - Hill_Valley_with_noise.csv
  - Hill_Valley_without_noise.csv
  - horse-colic.csv
  - house-votes-84.csv
  - hungarian.csv
  - hypothyroid.csv
  - ionosphere.csv
  - iris.csv
  - irish.csv
  - kdd_JapaneseVowels.csv
  - kdd_synthetic_control.csv
  - kr-vs-kp.csv
  - krkopt.csv
  - labor.csv
  - led7.csv
  - led24.csv
  - letter.csv
  - leukemia.csv
  - Leukemia_3c.csv
  - liver-disorder.csv
  - lupus.csv
  - lymph.csv
  - mfeat-factors.csv
  - mfeat-fourier.csv
  - mfeat-karhunen.csv
  - mfeat-morphological.csv
  - mfeat-pixel.csv
  - mfeat-zernike.csv
  - mnist.csv
  - mofn-3-7-10.csv
  - molecular-biology_promoters.csv
  - monk1.csv
  - monk2.csv
  - monk3.csv
  - mushroom.csv
  - mux6.csv
  - new-thyroid.csv
  - nursery.csv
  - oh0.wc.csv
  - oh5.wc.csv
  - oh10.wc.csv
  - oh15.wc.csv
  - optdigits.csv
  - page-blocks.csv
  - parity5+5.csv
  - parity5.csv
  - pasture.csv
  - pendigits.csv
  - PIE10P.csv
  - pima.csv
  - postoperative-patient-data.csv
  - prnn_crabs.csv
  - prnn_fglass.csv
  - prnn_synth.csv
  - profb.csv
  - promoters.csv
  - satimage.csv
  - schizo.csv
  - segmentation.csv
  - shuttle.csv
  - sleep.csv
  - SMK-CAN-187.csv
  - solar-flare_1.csv
  - solar-flare_2.csv
  - sonar.csv
  - soybean.csv
  - spambase.csv
  - spect.csv
  - spectf.csv
  - spectrometer.csv
  - splice.csv
  - sylva_agnostic.csv
  - sylva_prior.csv
  - tae.csv
  - threeOf9.csv
  - tic-tac-toe.csv
  - tokyo1.csv
  - TOX-171.csv
  - tr11.wc.csv
  - tr12.wc.csv
  - tr23.wc.csv
  - tr31.wc.csv
  - tr41.wc.csv
  - tr45.wc.csv
  - vehicle.csv
  - vote.csv
  - vowel.csv
  - wap.wc.csv
  - waveform-21.csv
  - waveform-40.csv
  - white-clover.csv
  - wine-quality-red.csv
  - wine-quality-white.csv
  - wine-recognition.csv
  - xd6.csv
  - yeast.csv
  - zoo.csv
